re-introducing non silent fail

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -66,4 +66,10 @@ jobs:
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.access-token }}
         run: |
-          vendor/bin/phpcs --report=json ${CHANGED_FILES} | jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" ' | reviewdog -efm="%f:%l:%c:%m" -name="phpcs" -filter-mode="added" -fail-on-error=true -reporter=github-pr-review
+          JSON_REPORT=$(vendor/bin/phpcs --report=json ${{ env.CHANGED_FILES }} )
+          echo $JSON_REPORT | jq empty
+          if [ $? -ne 0 ]; then
+            echo "Invalid JSON"
+            exit 1
+          fi
+          echo $JSON_REPORT | jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" ' | reviewdog -efm="%f:%l:%c:%m" -name="phpcs" -filter-mode="added" -fail-on-error=true -reporter=github-pr-review
