Processing each file one by one

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -54,7 +54,7 @@ jobs:
       - name: Get list of changed files
         id: files
         run: |
-          echo "CHANGED_FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- . ':!tests' | grep '\.php$' | sed 's/ /\\ /g' | sed 's|^|\"|' | sed 's|$|\"|' | tr '\n' ' ')" >> $GITHUB_ENV
+          echo "CHANGED_FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- . ':!tests' | grep '\.php$' )" >> $GITHUB_ENV
 
       # ------------------------------------------------------------------------------
       # PHPCS
@@ -66,24 +66,55 @@ jobs:
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.access-token }}
         run: |
-          # Run phpcs and capture both the output and the exit code
-          JSON_REPORT=$(vendor/bin/phpcs --report=json ${{ env.CHANGED_FILES }} || echo "")
-          PHPCS_EXIT_CODE=$?
+          CHANGED_FILES=$(echo ${{ env.CHANGED_FILES }})
+          echo "$CHANGED_FILES"
+          NEED_TO_FAIL=0
 
-          # Check if phpcs produced a JSON report
-          if [ -z "$JSON_REPORT" ]; then
-            echo "No JSON report generated by phpcs"
-            exit $PHPCS_EXIT_CODE
+          MERGED_JSON="[]"
+          if [ -n "$CHANGED_FILES" ]; then
+            echo "$CHANGED_FILES"
+            IFS=$'\n' read -d '' -r -a FILE_ARRAY <<<"$CHANGED_FILES"
+            echo $?
+            declare -p FILE_ARRAY
+              for FILE in "${FILE_ARRAY[@]}"; do
+                  # New line
+                  echo ""
+                  echo "vendor/bin/phpcs --report=json \"$FILE\""
+                  JSON_REPORT=$(vendor/bin/phpcs --report=json "$FILE" 2>/dev/null || echo "")
+                  PHPCS_EXIT_CODE=$?
+
+                  echo "JSON REPORT FOR FILE $FILE: $JSON_REPORT"
+
+                  # Validate the JSON
+                  if [ -n "$JSON_REPORT" ] && echo "$JSON_REPORT" | jq empty; then
+                      # Check if the JSON report contains valid "files" key
+                      if echo "$JSON_REPORT" | jq -e '.files' > /dev/null; then
+                          MERGED_JSON=$(echo "$MERGED_JSON" | jq --argjson report "$JSON_REPORT" '. + [$report]')
+                      fi
+                  fi
+
+                  # check if PHPCS_EXIT_CODE is not 0
+                  if [ $PHPCS_EXIT_CODE -ne 0 ]; then
+                      NEED_TO_FAIL=1
+                  fi
+              done <<< "$CHANGED_FILES"
           fi
 
-          # Validate the JSON
-          if ! echo "$JSON_REPORT" | jq empty; then
-            echo "Invalid JSON: $JSON_REPORT"
-            exit 1
+          echo "Merged JSON is: $MERGED_JSON"
+          # Check if phpcs produced a JSON report
+          if [ -z "$MERGED_JSON" ]; then
+              echo "No JSON report generated by phpcs"
+              exit 1
+          fi
+
+          # Validate the merged JSON
+          if ! echo "$MERGED_JSON" | jq empty; then
+              echo "Invalid JSON: $MERGED_JSON"
+              exit 1
           fi
 
           # Process JSON and run reviewdog
-          echo "$JSON_REPORT" | jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" ' | reviewdog -efm="%f:%l:%c:%m" -name="phpcs" -filter-mode="added" -fail-on-error=true -reporter=github-pr-review
+          echo "$MERGED_JSON" | jq -r 'map(.files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)") | .[]'
 
           # Exit with the original phpcs exit code
-          exit $PHPCS_EXIT_CODE
+          exit $NEED_TO_FAIL
